name: ethiopian_idol
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  chapa_unofficial:
    git: https://github.com/mrnpro/ChapaFlutter.git
  cupertino_icons: ^1.0.2
  curved_labeled_navigation_bar: ^2.0.2
  hero_animation: ^1.1.2
  carousel_slider: ^4.2.1
  googleapis_auth: ^1.4.1
  googleapis: ^11.4.0
  url_launcher: ^6.1.12
  shimmer: ^3.0.0
  provider: ^6.0.5
  flutter_native_splash: ^2.3.2
  youtube_player_flutter: ^8.1.2
  file_picker: ^5.3.3
  chapasdk: ^0.0.6
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  modal_progress_hud_nsn: ^0.4.0
  shared_preferences: ^2.2.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Outfit-black,
      fonts:
        - asset: fonts/Outfit-VariableFont_wght.ttf
    - family: Poppins
      fonts:
            - asset: fonts/Poppins/Poppins-Bold.ttf
              weight: 700
            - asset: fonts/Poppins/Poppins-Regular.ttf
              weight: 200
